language: node_js
node_js:
  - "7"
cache: yarn
script:
  - yarn lint
  - yarn test -- --coverage
  - yarn build:storybook
branches:
  only:
    - master
    - /^greenkeeper/.*$/
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
   branch: master
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
