language: node_js
node_js:
  - "lts/*"
cache: yarn
stages:
  - test
  - name: deploy
    if: branch = master
  - name: release
    if: branch = master AND type != pull_request
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test --ci --coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script:
        - yarn build
        - yarn build:storybook
      deploy:
        local_dir: .docs
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        on:
          branch: master
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn release
        on:
          branch: master
