language: node_js
node_js:
  - "8"
  - "6"
cache: yarn
branches:
  only:
    - master
    - /^greenkeeper/.*$/
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
   branch: master
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn test -- --coverage
  - yarn build:storybook
after_script: greenkeeper-lockfile-upload
after_success: bash <(curl -s https://codecov.io/bash)
